In [13]:
import pandas as pd

## Step 1: Preclean

In [14]:
qbdataroute = "../dirtyresources/FantasyPros_Fantasy_Football_Statistics_QB.csv"
qbdataDF = pd.read_csv(qbdataroute)
qbdataDF

,Rank,Player,CMP,ATT,PCT,YDS,Y/A,TD,INT,SACKS,ATT.1,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Josh Allen (BUF),319.0,460.0,69.3,"3,668",8.0,25.0,10.0,40.0,112.0,579.0,14.0,3.0,17.0,374.5,22.0,99.1%
1,2.0,Drake Maye (NE),354.0,492.0,72.0,"4,394",8.9,31.0,8.0,47.0,103.0,450.0,4.0,3.0,17.0,359.9,21.2,97.9%
2,3.0,Matthew Stafford (LAR),388.0,597.0,65.0,"4,707",7.9,46.0,8.0,23.0,29.0,1.0,0.0,3.0,17.0,358.3,21.1,92.0%
3,4.0,Trevor Lawrence (JAC),341.0,560.0,60.9,"4,007",7.2,29.0,12.0,41.0,82.0,359.0,9.0,3.0,17.0,350.1,20.6,86.0%
4,5.0,Caleb Williams (CHI),330.0,568.0,58.1,"3,942",6.9,27.0,7.0,24.0,77.0,383.0,3.0,1.0,17.0,325.3,19.1,86.4%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114.0,Kyle Allen (BUF),0.0,2.0,0.0,0,0.0,0.0,0.0,0.0,3.0,-3.0,0.0,0.0,4.0,-0.3,-0.1,0.7%
114,115.0,Jimmy Garoppolo (LAR),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,9.0,-10.0,0.0,0.0,5.0,-1.0,-0.2,1.8%
115,116.0,Jalen Milroe (SEA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,4.0,-1.6,-0.4,14.6%
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
renamedqbdatadf = qbdataDF.rename(columns={'Rank':'QBID', 'ATT':'PassingATT', 'YDS':'PassingYDS', 'Y/A': 'YardsPerThrow', 'TD':'PassingTD', 'ATT.1':'RushingATT', 
                                            'YDS.1': 'RushingYDS', 'TD.1': "RushingTD", "FL": "FumblesLost", 'G': 'Gamesplayed', 'FPTS/G': 'FPTSPerGame'})
renamedqbdatadf

,QBID,Player,CMP,PassingATT,PCT,PassingYDS,YardsPerThrow,PassingTD,INT,SACKS,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Josh Allen (BUF),319.0,460.0,69.3,"3,668",8.0,25.0,10.0,40.0,112.0,579.0,14.0,3.0,17.0,374.5,22.0,99.1%
1,2.0,Drake Maye (NE),354.0,492.0,72.0,"4,394",8.9,31.0,8.0,47.0,103.0,450.0,4.0,3.0,17.0,359.9,21.2,97.9%
2,3.0,Matthew Stafford (LAR),388.0,597.0,65.0,"4,707",7.9,46.0,8.0,23.0,29.0,1.0,0.0,3.0,17.0,358.3,21.1,92.0%
3,4.0,Trevor Lawrence (JAC),341.0,560.0,60.9,"4,007",7.2,29.0,12.0,41.0,82.0,359.0,9.0,3.0,17.0,350.1,20.6,86.0%
4,5.0,Caleb Williams (CHI),330.0,568.0,58.1,"3,942",6.9,27.0,7.0,24.0,77.0,383.0,3.0,1.0,17.0,325.3,19.1,86.4%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,114.0,Kyle Allen (BUF),0.0,2.0,0.0,0,0.0,0.0,0.0,0.0,3.0,-3.0,0.0,0.0,4.0,-0.3,-0.1,0.7%
114,115.0,Jimmy Garoppolo (LAR),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,9.0,-10.0,0.0,0.0,5.0,-1.0,-0.2,1.8%
115,116.0,Jalen Milroe (SEA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,1.0,4.0,-1.6,-0.4,14.6%
116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
wrdataroute = "../dirtyresources/FantasyPros_Fantasy_Football_Statistics_WR.csv"
wrdataDF = pd.read_csv(wrdataroute)
wrdataDF

,Rank,Player,TGT,TGT %,REC,YDS,Y/R,20+,TD,ATT,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Puka Nacua (LAR),166.0,28.6,129.0,"1,715",13.3,27.0,10.0,10.0,105.0,1.0,1.0,16.0,375.0,23.4,98.6%
1,2.0,Jaxon Smith-Njigba (SEA),163.0,36.0,119.0,"1,793",15.1,27.0,10.0,7.0,36.0,0.0,1.0,17.0,359.9,21.2,99.0%
2,3.0,Amon-Ra St. Brown (DET),172.0,31.4,117.0,"1,401",12.0,19.0,11.0,3.0,9.0,0.0,0.0,17.0,324.0,19.1,98.2%
3,4.0,Ja'Marr Chase (CIN),185.0,30.2,125.0,"1,412",11.3,15.0,8.0,3.0,14.0,0.0,1.0,16.0,313.6,19.6,98.3%
4,5.0,George Pickens (DAL),137.0,22.7,93.0,"1,429",15.4,22.0,9.0,0.0,0.0,0.0,0.0,17.0,291.9,17.2,92.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,334.0,Mecole Hardman Jr. (BUF),1.0,0.2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,-2.0,-1.0,0.6%
335,334.0,Jamal Agnew (FA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,-2.0,-0.2,0.0%
336,337.0,Myles Price (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,16.0,-6.0,-0.4,0.6%
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
renamedwrdatadf = wrdataDF.rename(columns={'Rank':'WRID', 'YDS':'RecYDS', 'Y/R': 'YardsPerReception','LG': 'Longest', '20+': '20YardsorMore', 'TD':'RecTD', 'ATT':'RushingATT', 
                         'YDS.1': 'RushingYDS', 'TD.1': "RushingTD", "FL": "FumblesLost", 'G': 'Gamesplayed', 'FPTS/G': 'FPTSPerGame'})
renamedwrdatadf

,WRID,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Puka Nacua (LAR),166.0,28.6,129.0,"1,715",13.3,27.0,10.0,10.0,105.0,1.0,1.0,16.0,375.0,23.4,98.6%
1,2.0,Jaxon Smith-Njigba (SEA),163.0,36.0,119.0,"1,793",15.1,27.0,10.0,7.0,36.0,0.0,1.0,17.0,359.9,21.2,99.0%
2,3.0,Amon-Ra St. Brown (DET),172.0,31.4,117.0,"1,401",12.0,19.0,11.0,3.0,9.0,0.0,0.0,17.0,324.0,19.1,98.2%
3,4.0,Ja'Marr Chase (CIN),185.0,30.2,125.0,"1,412",11.3,15.0,8.0,3.0,14.0,0.0,1.0,16.0,313.6,19.6,98.3%
4,5.0,George Pickens (DAL),137.0,22.7,93.0,"1,429",15.4,22.0,9.0,0.0,0.0,0.0,0.0,17.0,291.9,17.2,92.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,334.0,Mecole Hardman Jr. (BUF),1.0,0.2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,-2.0,-1.0,0.6%
335,334.0,Jamal Agnew (FA),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,-2.0,-0.2,0.0%
336,337.0,Myles Price (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,16.0,-6.0,-0.4,0.6%
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
rbdataroute = "../dirtyresources/FantasyPros_Fantasy_Football_Statistics_RB.csv"
rbdataDF = pd.read_csv(rbdataroute)
rbdataDF

,Rank,Player,ATT,YDS,Y/A,LG,20+,TD,TGT,REC,YDS.1,Y/R,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Christian McCaffrey (SF),311.0,"1,202",3.9,41.0,3.0,10.0,129.0,102.0,924.0,9.1,7.0,0.0,17.0,416.6,24.5,97.6%
1,2.0,Bijan Robinson (ATL),287.0,"1,478",5.1,93.0,8.0,7.0,103.0,79.0,820.0,10.4,4.0,3.0,17.0,370.8,21.8,94.8%
2,3.0,Jahmyr Gibbs (DET),243.0,"1,223",5.0,78.0,10.0,13.0,94.0,77.0,616.0,8.0,5.0,1.0,17.0,366.9,21.6,94.8%
3,4.0,Jonathan Taylor (IND),323.0,"1,585",4.9,83.0,9.0,18.0,55.0,46.0,378.0,8.2,2.0,1.0,17.0,362.3,21.3,94.0%
4,5.0,De'Von Achane (MIA),238.0,"1,350",5.7,59.0,13.0,8.0,85.0,67.0,488.0,7.3,4.0,0.0,16.0,322.8,20.2,94.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,216.0,Brennan Clay (DEN),0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
216,217.0,Travis Homer (PIT),1.0,-2,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,-0.2,0.0,0.6%
217,217.0,Nyheim Miller-Hines (FA),2.0,-2,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,-0.2,-0.1,0.0%
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
renamedrbdatadf = rbdataDF.rename(columns={'Rank':'RBID','ATT':'RushingATT', 'YDS':'RushingYDS', 'Y/A': 'YardsPerATT','LG': 'Longest', '20+': '20YardsorMore', 'TD':'RushingTD', 
                                            'YDS.1': 'RecYDS', 'TD.1': "RecTD", "Y/R": "YardsPerRec", "FL": "FumblesLost", 'G': 'Gamesplayed', 'FPTS/G': 'FPTSPerGame'})
renamedrbdatadf

,RBID,Player,RushingATT,RushingYDS,YardsPerATT,Longest,20YardsorMore,RushingTD,TGT,REC,RecYDS,YardsPerRec,RecTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Christian McCaffrey (SF),311.0,"1,202",3.9,41.0,3.0,10.0,129.0,102.0,924.0,9.1,7.0,0.0,17.0,416.6,24.5,97.6%
1,2.0,Bijan Robinson (ATL),287.0,"1,478",5.1,93.0,8.0,7.0,103.0,79.0,820.0,10.4,4.0,3.0,17.0,370.8,21.8,94.8%
2,3.0,Jahmyr Gibbs (DET),243.0,"1,223",5.0,78.0,10.0,13.0,94.0,77.0,616.0,8.0,5.0,1.0,17.0,366.9,21.6,94.8%
3,4.0,Jonathan Taylor (IND),323.0,"1,585",4.9,83.0,9.0,18.0,55.0,46.0,378.0,8.2,2.0,1.0,17.0,362.3,21.3,94.0%
4,5.0,De'Von Achane (MIA),238.0,"1,350",5.7,59.0,13.0,8.0,85.0,67.0,488.0,7.3,4.0,0.0,16.0,322.8,20.2,94.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,216.0,Brennan Clay (DEN),0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
216,217.0,Travis Homer (PIT),1.0,-2,-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,-0.2,0.0,0.6%
217,217.0,Nyheim Miller-Hines (FA),2.0,-2,-1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,-0.2,-0.1,0.0%
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
tedataroute = "../dirtyresources/FantasyPros_Fantasy_Football_Statistics_TE.csv"
tedataDF = pd.read_csv(tedataroute)
tedataDF

,Rank,Player,TGT,TGT %,REC,YDS,Y/R,20+,TD,ATT,YDS.1,TD.1,FL,G,FPTS,FPTS/G,ROST
0,1.0,Trey McBride (ARI),169.0,27.5,126.0,"1,239",9.8,12.0,11.0,0.0,0.0,0.0,0.0,17.0,315.9,18.6,93.8%
1,2.0,Kyle Pitts Sr. (ATL),118.0,22.8,88.0,928,10.5,12.0,5.0,0.0,0.0,0.0,0.0,17.0,210.8,12.4,92.4%
2,3.0,Travis Kelce (KC),108.0,19.7,76.0,851,11.2,9.0,5.0,1.0,1.0,0.0,0.0,17.0,193.2,11.4,89.5%
3,4.0,Tyler Warren (IND),112.0,20.9,76.0,817,10.8,10.0,4.0,6.0,8.0,1.0,0.0,17.0,188.5,11.1,95.6%
4,5.0,Jake Ferguson (DAL),102.0,17.1,82.0,600,7.3,2.0,8.0,1.0,1.0,0.0,2.0,17.0,188.1,11.1,81.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,189.0,Andrew DePaola (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
196,189.0,Tyler Ott (WAS),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
197,198.0,Carson Towt (IND),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
renamedtedatadf = tedataDF.rename(columns={'Rank':'TEID', 'YDS':'RecYDS', 'Y/R': 'YardsPerReception','LG': 'Longest', '20+': '20YardsorMore', 'TD':'RecTD', 'ATT':'RushingATT', 
                         'YDS.1': 'RushingYDS', 'TD.1': "RushingTD", "FL": "FumblesLost", 'G': 'Gamesplayed', 'FPTS/G': 'FPTSPerGame'})
renamedtedatadf

,TEID,Player,TGT,TGT %,REC,RecYDS,YardsPerReception,20YardsorMore,RecTD,RushingATT,RushingYDS,RushingTD,FumblesLost,Gamesplayed,FPTS,FPTSPerGame,ROST
0,1.0,Trey McBride (ARI),169.0,27.5,126.0,"1,239",9.8,12.0,11.0,0.0,0.0,0.0,0.0,17.0,315.9,18.6,93.8%
1,2.0,Kyle Pitts Sr. (ATL),118.0,22.8,88.0,928,10.5,12.0,5.0,0.0,0.0,0.0,0.0,17.0,210.8,12.4,92.4%
2,3.0,Travis Kelce (KC),108.0,19.7,76.0,851,11.2,9.0,5.0,1.0,1.0,0.0,0.0,17.0,193.2,11.4,89.5%
3,4.0,Tyler Warren (IND),112.0,20.9,76.0,817,10.8,10.0,4.0,6.0,8.0,1.0,0.0,17.0,188.5,11.1,95.6%
4,5.0,Jake Ferguson (DAL),102.0,17.1,82.0,600,7.3,2.0,8.0,1.0,1.0,0.0,2.0,17.0,188.1,11.1,81.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,189.0,Andrew DePaola (MIN),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
196,189.0,Tyler Ott (WAS),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0%
197,198.0,Carson Towt (IND),0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
kickdataroute = "../dirtyresources/FantasyPros_Fantasy_Football_Statistics_K.csv"
kickdataDF = pd.read_csv(kickdataroute)
kickdataDF

,Rank,Player,FG,FGA,PCT,LG,1-19,20-29,30-39,40-49,50+,XPT,XPA,G,FPTS,FPTS/G,ROST
0,1.0,Jason Myers (SEA),41.0,48.0,85.4,57.0,0.0,5.0,14.0,13.0,9.0,48.0,48.0,17.0,202.0,11.9,84.5%
1,2.0,Ka'imi Fairbairn (HOU),44.0,48.0,91.7,57.0,0.0,8.0,11.0,16.0,9.0,28.0,28.0,15.0,194.0,12.9,68.8%
2,3.0,Brandon Aubrey (DAL),36.0,42.0,85.7,64.0,0.0,10.0,5.0,10.0,11.0,47.0,48.0,17.0,187.6,11.0,94.3%
3,4.0,Cameron Dicker (LAC),38.0,41.0,92.7,59.0,0.0,7.0,14.0,12.0,5.0,34.0,35.0,17.0,170.0,10.0,85.5%
4,5.0,Cam Little (JAC),30.0,34.0,88.2,68.0,0.0,5.0,9.0,8.0,8.0,50.0,51.0,17.0,164.0,9.6,72.5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,43.0,Connor Hughes (DAL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
60,43.0,Garrett Lindholm (ATL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
61,43.0,Saverio Rocca (WAS),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
renamedkickDataDF = kickdataDF.rename(columns={ 'Rank': 'KickID', 'FG': 'FG Made', 'FGA': 'FG Attempted', 'LG': 'Longest', 'XPT': 'Extra Point Made', 'XPA': 'Extra Points Attempted', 'G': 'Games Played', 'FPTSPerGame': 'FPTSPerGame' })
renamedkickDataDF

,KickID,Player,FG Made,FG Attempted,PCT,Longest,1-19,20-29,30-39,40-49,50+,Extra Point Made,Extra Points Attempted,Games Played,FPTS,FPTS/G,ROST
0,1.0,Jason Myers (SEA),41.0,48.0,85.4,57.0,0.0,5.0,14.0,13.0,9.0,48.0,48.0,17.0,202.0,11.9,84.5%
1,2.0,Ka'imi Fairbairn (HOU),44.0,48.0,91.7,57.0,0.0,8.0,11.0,16.0,9.0,28.0,28.0,15.0,194.0,12.9,68.8%
2,3.0,Brandon Aubrey (DAL),36.0,42.0,85.7,64.0,0.0,10.0,5.0,10.0,11.0,47.0,48.0,17.0,187.6,11.0,94.3%
3,4.0,Cameron Dicker (LAC),38.0,41.0,92.7,59.0,0.0,7.0,14.0,12.0,5.0,34.0,35.0,17.0,170.0,10.0,85.5%
4,5.0,Cam Little (JAC),30.0,34.0,88.2,68.0,0.0,5.0,9.0,8.0,8.0,50.0,51.0,17.0,164.0,9.6,72.5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,43.0,Connor Hughes (DAL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
60,43.0,Garrett Lindholm (ATL),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
61,43.0,Saverio Rocca (WAS),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0%
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
renamedqbdatadf.to_csv("../Resources/FantasyPros_Fantasy_Football_Statistics_QB.csv", index=False)
renamedwrdatadf.to_csv("../Resources/FantasyPros_Fantasy_Football_Statistics_WR.csv", index=False)
renamedrbdatadf.to_csv("../Resources/FantasyPros_Fantasy_Football_Statistics_RB.csv", index=False)
renamedtedatadf.to_csv("../Resources/FantasyPros_Fantasy_Football_Statistics_TE.csv", index=False)
renamedkickDataDF.to_csv("../Resources/FantasyPros_Fantasy_Football_Statistics_K.csv", index = False)